"""empty message

Revision ID: eb45bca11515
Revises: 
Create Date: 2019-07-17 22:18:05.254132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb45bca11515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_edited_date', sa.DateTime(), nullable=True),
    sa.Column('last_edited_by', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.Column('account', sa.Float(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('validation', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
